server:
  port: 8080

spring:
  application:
    name: Lesson
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/lessons
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'





