server:
  port: 8081

spring:
  application:
    name: admin
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/admin_db
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'false'





