server:
  port: 8082

spring:
  application:
    name: Book
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/book_db
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'


logging:
  file:
    name: logs/application.log
    path: logs
  level:
    com:
      sivalabs: DEBUG
    org:
      springframework: INFO
      hibernate:
        validator: DEBUG